#'this script loads the .csv files generated by find_state_markers.R and removes
#'(or better, puts into a separate column) the genes which were already present
#'in their respective known_cells_genes.csv, meaning that what is left are
#'genes which do behave just like the cells' markers *only under a specific patient
#'condition* (healthy, inflamed or not inflamed) and that were not already known
#'
#'Usage: just edit the "dataset" variable to the target dataset's name,
#'       and set the list of patient IDs "N", "I", and "H" with the respective IDs.


#'set it to whatever you like. The working directory path should contain, at least,
#'the main.R script
setwd("~/Scrivania/CHL_Project")
source("utils.R")

#'dataset name + the list of patients for each condition
dataset = "CO_STR"
N <- list("N107306", "N124246", "N104152", "N104689")
I <- list("I130084")
H <- list("H197396")

states_to_load <- list(N, I, H)

#dataset path
p <- paste0(getwd(), "/", dataset)

optimal_clusters <- list()

i <- 1
cells_data  <- read_csv_data(paste0(p, "/known_cells_genes.csv"))
cells_names <- names(cells_data)

csvs <- list()

#TI_IMM_state_markers_I
for(i in 1:length(states_to_load))
{
  patient_type <- substr(states_to_load[[i]][[1]],1,1)
  
  #loads one of the known state markers file from the folder
  filename <- paste0(p, "/",dataset, "_state_markers_",patient_type, ".csv")
  curr_csv <- read_csv_data(filename)
  
  to_add <- c('cell_name,new_genes,known_genes')
  
  #for each cell we now need to get the newly found genes (meaning, the ones not
  #included in the known_cells_genes.csv file, which can be found by intersection)
  #they can be obtained simply by subtracting the known_cells_genes from it 
  for(i in 1:length(cells_data))
  {
    #loads the current cell's known genes
    known_cell_markers <- cells_data[[i]]
    #print(known_cell_markers)
    
    #current genes
    file_cell_marker <- curr_csv[[i]]
    
    #finds the new_genes by set subtraction, and the remainder are the already known genes
    new_genes           <- paste0(setdiff(file_cell_marker, known_cell_markers), collapse=';')
    already_known_genes <- paste0(intersect(file_cell_marker, known_cell_markers), collapse=';')
    
    tmp <- paste0(list(cells_names[[i]], new_genes, already_known_genes), collapse=',')
    to_add <- c(to_add, tmp)
  }
  
  #'saves the file as <dataset name>_state_markers_splitted_<condition>.csv
  path <- paste0(p, "/",dataset, "_state_markers_splitted_", patient_type, ".csv")
  file.create(path)
  file_conn = file(path)
  writeLines(to_add, file_conn)
  close(file_conn)
}


